/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.services.UserBookingService;
import org.example.util4.UserServiceUtil;

import javax.imageio.IIOException;
import java.io.IOException;
import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello, World!";
    }
    public static void main(String[] args) {
        System.out.println("Welcome to ticket booking service");
        Scanner scanner = new Scanner(System.in);
        int choice = 0;
        UserBookingService  userBookingService;
        try{
            userBookingService = new UserBookingService();
        }catch(IOException ex ){
            System.out.println("Failed to load UserBookingService");
            ex.printStackTrace();
            return;
        }
        while(choice != 7){
            System.out.println("Please choose one of the following options");
            System.out.println("1. Create a new user");
            System.out.println("2. Login  [existing user]");
            System.out.println("3. Fetch Booking Details");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel Booking");
            System.out.println("7. Exit");
            choice = scanner.nextInt();
            switch (choice){
                case 1:
                    System.out.println("Enter username: ");
                    String username = scanner.next();
                    System.out.println("Enter password: ");
                    String password = scanner.next();
                    user userToSignUp = new user(username,password, UserServiceUtil.hashPassword(password),new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUpUser(userToSignUp);
                    break;
                case 2:
                    System.out.println("Enter username: ");
                    String userName = scanner.next();
                    System.out.println("Enter password: ");
                    String password1 = scanner.next();
                    user userToLogin = new  user(userName,password1,UserServiceUtil.hashPassword(password1),new ArrayList<>(), UUID.randomUUID().toString());
                    userToLogin.setName(userName);
                    userToLogin.setPassword(password1);
                    try{
                        UserBookingService userBookingService1= new UserBookingService(userToLogin);
                    }catch(IOException ex ){
                        return;
                    }
                    userBookingService.logInUser(userToLogin);
                    break;
                case 3:
                    System.out.println("Fetch your booking Details");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Enter the source: ");
                    String source = scanner.next();
                    System.out.println("Enter the destination: ");
                    String destination = scanner.next();
                    if(userBookingService.fetchTrains(source,destination)==true){
                        System.out.println("Train is available kindly go ahead with the booking ");
                    }
                    break;
                case 5:
                    System.out.println("Enter the source: ");
                    String source1 = scanner.next();
                    System.out.println("Enter the destination: ");
                    String destination1 = scanner.next();
                    System.out.println("Enter the row number: ");
                    Integer rowNumber = scanner.nextInt();
                    System.out.println("Enter the column number: ");
                    Integer colNumber = scanner.nextInt();
                    userBookingService.bookTicket(source1,destination1,rowNumber,colNumber);
                    break;
                case 6:
                    System.out.println("Enter the TicketID: ");
                    String ticketID = scanner.next();
                    userBookingService.cancelBooking(ticketID);
                    break;
                default:
                    System.out.println("Exiting from the app");
                    break;

            }
        }
    }
}

